In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('auto_mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [4]:
#Problem statement : Retrieve details of all the cars built in year 72.

df.loc[df['model_year']==72].head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
57,24.0,4,113.0,95.0,2278,15.5,72,japan,toyota corona hardtop
58,25.0,4,97.5,80.0,2126,17.0,72,usa,dodge colt hardtop
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
60,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
61,21.0,4,122.0,86.0,2226,16.5,72,usa,ford pinto runabout

In [5]:
#Problem statement : Retrieve details of all the cars built in Japan having 6 cylinders

df[(df['origin']=='japan') & (df['cylinders']==6)].head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
123,20.0,6,156.0,122.0,2807,13.5,73,japan,toyota mark ii
210,19.0,6,156.0,108.0,2930,15.5,76,japan,toyota mark ii
241,22.0,6,146.0,97.0,2815,14.5,77,japan,datsun 810
333,32.7,6,168.0,132.0,2910,11.4,80,japan,datsun 280-zx
361,25.4,6,168.0,116.0,2900,12.6,81,japan,toyota cressida

In [6]:
# Fuel efficient
# MPG > 29, Horsepower < 93.5,
# Weight < 2500

df.loc[(df['mpg']>29) & (df['horsepower']<93.5) & (df['weight']<2500)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
51,30.0,4,79.0,70.0,2074,19.5,71,europe,peugeot 304
52,30.0,4,88.0,76.0,2065,14.5,71,europe,fiat 124b
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
129,31.0,4,79.0,67.0,1950,19.0,74,japan,datsun b210
...,...,...,...,...,...,...,...,...,...
384,32.0,4,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
385,38.0,4,91.0,67.0,1995,16.2,82,japan,datsun 310 gx
391,36.0,4,135.0,84.0,2370,13.0,82,usa,dodge charger 2.2
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage

In [10]:
# Muscle cars
# Displacement >262, Horsepower > 126, Weight in range[2800, 3600]

df.loc[(df['displacement']>262) & (df['horsepower']>126) & (df['weight']>=2800) & (df['weight']<=3600)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
10,15.0,8,383.0,170.0,3563,10.0,70,usa,dodge challenger se
13,14.0,8,455.0,225.0,3086,10.0,70,usa,buick estate wagon (sw)
121,15.0,8,318.0,150.0,3399,11.0,73,usa,dodge dart custom
166,13.0,8,302.0,129.0,3169,12.0,75,usa,ford mustang ii
251,20.2,8,302.0,139.0,3570,12.8,78,usa,mercury monarch ghia
262,19.2,8,305.0,145.0,3425,13.2,78,usa,chevrolet monte carlo landau
264,18.1,8,302.0,139.0,3205,11.2,78,usa,ford futura

In [11]:
# SUV
# Horsepower > 140 , Weight > 4500

df.iloc[(df['horsepower'] > 140) & (df['weight']>=4500)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
42,12.0,8,383.0,180.0,4955,11.5,71,usa,dodge monaco (sw)
43,13.0,8,400.0,170.0,4746,12.0,71,usa,ford country squire (sw)
44,13.0,8,400.0,175.0,5140,12.0,71,usa,pontiac safari (sw)
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
68,13.0,8,350.0,155.0,4502,13.5,72,usa,buick lesabre custom
90,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
94,13.0,8,440.0,215.0,4735,11.0,73,usa,chrysler new yorker brougham
95,12.0,8,455.0,225.0,4951,11.0,73,usa,buick electra 225 custom
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
104,12.0,8,400.0,167.0,4906,12.5,73,usa,ford country
105,13.0,8,360.0,170.0,4654,13.0,73,usa,plymouth custom suburb
137,13.0,8,350.0,150.0,4699,14.5,74,usa,buick century luxus (sw)
156,16.0,8,400.0,170.0,4668,11.5,75,usa,pontiac catalina
159,14.0,8,351.0,148.0,4657,13.5,75,usa,ford ltd

In [13]:
# Racecar
# Weight <2223, acceleration > 17
df.dropna(inplace=True)

df.loc[(df['weight']<2223) & (df['acceleration'] > 17)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
51,30.0,4,79.0,70.0,2074,19.5,71,europe,peugeot 304
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
55,27.0,4,97.0,60.0,1834,19.0,71,europe,volkswagen model 111
56,26.0,4,91.0,70.0,1955,20.5,71,usa,plymouth cricket
79,26.0,4,96.0,69.0,2189,18.0,72,europe,renault 12 (sw)
102,26.0,4,97.0,46.0,1950,21.0,73,europe,volkswagen super beetle
117,29.0,4,68.0,49.0,1867,19.5,73,europe,fiat 128
129,31.0,4,79.0,67.0,1950,19.0,74,japan,datsun b210
131,32.0,4,71.0,65.0,1836,21.0,74,japan,toyota corolla 1200
145,32.0,4,83.0,61.0,2003,19.0,74,japan,datsun 710
181,33.0,4,91.0,53.0,1795,17.5,75,japan,honda civic cvcc
195,29.0,4,85.0,52.0,2035,22.2,76,usa,chevrolet chevette
196,24.5,4,98.0,60.0,2164,22.1,76,usa,chevrolet woody
198,33.0,4,91.0,53.0,1795,17.4,76,japan,honda civic
216,31.5,4,98.0,68.0,2045,18.5,77,japan,honda accord cvcc
218,36.0,4,79.0,58.0,1825,18.6,77,europe,renault 5 gtl
244,43.1,4,90.0,48.0,1985,21.5,78,europe,volkswagen rabbit custom diesel
246,32.8,4,78.0,52.0,1985,19.4,78,japan,mazda glc deluxe
247,39.4,4,85.0,70.0,2070,18.6,78,japan,datsun b210 gx
303,31.8,4,85.0,65.0,2020,19.2,79,japan,datsun 210
310,38.1,4,89.0,60.0,1968,18.8,80,japan,toyota corolla tercel
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
324,40.8,4,85.0,65.0,2110,19.2,80,japan,datsun 210
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
331,33.8,4,97.0,67.0,2145,18.0,80,japan,subaru dl
346,32.3,4,97.0,67.0,2065,17.8,81,japan,subaru
347,37.0,4,85.0,65.0,1975,19.4,81,japan,datsun 210 mpg
348,37.7,4,89.0,62.0,2050,17.3,81,japan,toyota tercel
376,37.0,4,91.0,68.0,2025,18.2,82,japan,mazda glc custom l
377,31.0,4,91.0,68.0,1970,17.6,82,japan,mazda glc custom
379,36.0,4,98.0,70.0,2125,17.3,82,usa,mercury lynx l
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup