In [1]:
import numpy as np
import pandas as pd

In [2]:
marks_A = {'Chemistry': [67,90,66,32], 
        'Physics': [45,92,72,40],  
          }
marks_A_df = pd.DataFrame(marks_A, index = ['Subodh', 'Ram', 'Abdul', 'John'])
marks_B = {'Chemistry': [72,45,60,98], 
        'Physics': [78,34,72,95],  
          }
marks_B_df = pd.DataFrame(marks_B, index = ['Nandini', 'Zoya', 'Shivam', 'James'])

Problem Statement:
The teacher wants to combine the marks of these students.

Solution:  
Using concatenation to combine the marks-

Syntax:

       pd.concat(data1, data2, sort)

In [4]:
pd.concat([marks_A_df , marks_B_df] , sort=False)

         Chemistry  Physics
Subodh          67       45
Ram             90       92
Abdul           66       72
John            32       40
Nandini         72       78
Zoya            45       34
Shivam          60       72
James           98       95

Using Merge in case of column mismatch
To resolve the above condition, the merge function can be used which joins two tables based on a key. 


Syntax:
       pd.merge(data1, data2, how = 'inner')

In [8]:
df3 = pd.merge(marks_A_df , marks_B_df , how='inner')
df3

Empty DataFrame
Columns: [Chemistry, Physics]
Index: []