Problem statement: 
The engineers at XYZ Custom Cars want to know the frequency distribution of different number of cylinders across different years.

Solution:
For such given condition, cross tab is used. It gives us a tabular representation of the frequency distribution

In [1]:
import numpy as np 
import pandas as pd

In [4]:
df = pd.read_csv('auto_mpg.csv')
df.dropna(inplace=True)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [6]:
cross_tab = pd.crosstab(df['model_year'],df['cylinders'])
cross_tab

cylinders   3   4  5   6   8
model_year
70          0   7  0   4  18
71          0  12  0   8   7
72          1  14  0   0  13
73          1  11  0   8  20
74          0  15  0   6   5
75          0  12  0  12   6
76          0  15  0  10   9
77          1  14  0   5   8
78          0  17  1  12   6
79          0  12  1   6  10
80          1  23  1   2   0
81          0  20  0   7   1
82          0  27  0   3   0