XYZ custom cars want to know the number of cars manufactured in each year.

This would require a grouping operation. Pandas supports a group by feature to group our data for aggregate operations.

Syntax:

       DataFrame.groupby(by = column_name, axis, sort)

Problem statement:
How many cars belong to each year?

Solution:
In addition to the groupby function, the count function can be used as shown below. Since, cars are counted by names in each model year, the ‘name’ column in a list is used to get the output as a DataFrame.

In [ ]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv('auto_mpg.csv')
data

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [3]:
data.groupby(['model_year']).count()[['name']]

            name
model_year
70            29
71            28
72            28
73            40
74            27
75            30
76            34
77            28
78            36
79            29
80            29
81            29
82            31

Problem Statement: 
Some senior engineers in XYZ custom cars want to understand about the effect of model year and number of cylinders on horsepower.

Solution: 
One of the engineers suggests about checking the mean, minimum and maximum horsepower based on number of cylinders and model year. For such requirement, the ‘agg’ function can be combined with groupby function as shown below:

In [4]:
#Creating a DataFrame grouped on cylinders and model_year and finding mean, min and max of horsepower
grouped_multiple = data.groupby(['cylinders','model_year']).agg({'horsepower':['mean','max','min']})

#Naming columns in grouped DataFrame
grouped_multiple.columns=['hp_mean','hp_max','hp_min']

#Reseting index 
grouped_multiple.reset_index(inplace=True)


grouped_multiple.head()

   cylinders  model_year     hp_mean  hp_max  hp_min
0          3          72   97.000000    97.0    97.0
1          3          73   90.000000    90.0    90.0
2          3          77  110.000000   110.0   110.0
3          3          80  100.000000   100.0   100.0
4          4          70   87.714286   113.0    46.0

Problem statement: 
The engineers at XYZ Custom Cars want to know about the relationship between model year and acceleration of cars.

In [6]:
relationData = data.groupby(['model_year']).apply(lambda x: x.sort_values('acceleration')).reset_index(drop=True)
relationData.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,origin,name
0,14.0,8,340.0,160.0,3609,8.0,usa,plymouth 'cuda 340
1,14.0,8,440.0,215.0,4312,8.5,usa,plymouth fury iii
2,15.0,8,390.0,190.0,3850,8.5,usa,amc ambassador dpl
3,14.0,8,454.0,220.0,4354,9.0,usa,chevrolet impala
4,15.0,8,400.0,150.0,3761,9.5,usa,chevrolet monte carlo