In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('auto_mpg.csv')
df.dropna(inplace=True)

# Problem Statement:
XYZ Custom cars want the data sorted according to the number of cylinders.

In [4]:
df.sort_values(by='cylinders')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
243,21.5,3,80.0,110.0,2720,13.5,77,japan,mazda rx-4
334,23.7,3,70.0,100.0,2420,12.5,80,japan,mazda rx-7 gs
111,18.0,3,70.0,90.0,2124,13.5,73,japan,maxda rx3
71,19.0,3,70.0,97.0,2330,13.5,72,japan,mazda rx2 coupe
237,30.5,4,98.0,63.0,2051,17.0,77,usa,chevrolet chevette
...,...,...,...,...,...,...,...,...,...
86,14.0,8,304.0,150.0,3672,11.5,73,usa,amc matador
85,13.0,8,350.0,175.0,4100,13.0,73,usa,buick century 350
285,17.0,8,305.0,130.0,3840,15.4,79,usa,chevrolet caprice classic
92,13.0,8,351.0,158.0,4363,13.0,73,usa,ford ltd
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu

# Problem Statement:
There is a requirement in which the cars that have lowest acceleration must be assessed. It is also to be checked that which cars have higher horsepower despite having lower acceleration.

In [6]:
# In this case, the data must be sorted in ascending order of acceleration and descending order of horsepower as follows:
df.sort_values(by=['acceleration','horsepower'], ascending=(1,0))

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
116,16.0,8,400.0,230.0,4278,9.5,73,usa,pontiac grand prix
...,...,...,...,...,...,...,...,...,...
195,29.0,4,85.0,52.0,2035,22.2,76,usa,chevrolet chevette
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
299,27.2,4,141.0,71.0,3190,24.8,79,europe,peugeot 504