In [23]:
import numpy as np
import pandas as pd

In [24]:
# Creating a synthetic dataset with different types of missing values
data = {
    'A': [1, 2, np.nan, 4, 9999, 6, '?', 8, 9],
    'B': [5, '?', 7, 8, 9, np.nan, 11, 9999, 13],
    'C': [9999, 15, 16, '?', 18, np.nan, 20, 21, 22]
}

In [25]:
#Converting the data set into dataframe
df = pd.DataFrame(data)

In [38]:
print("Original Data: ")
df

Original Data:

     A    B    C
0    1    5  NaN
1    2  NaN   15
2  NaN    7   16
3    4    8  NaN
4  NaN    9   18
5    6  NaN  NaN
6  NaN   11   20
7    8  NaN   21
8    9   13   22

In [39]:
# Replace '?' and 9999 with NaN for standard handling
df.replace(['?',9999], np.nan , inplace=True)
print(df)
df.dtypes

     A    B    C
0    1    5  NaN
1    2  NaN   15
2  NaN    7   16
3    4    8  NaN
4  NaN    9   18
5    6  NaN  NaN
6  NaN   11   20
7    8  NaN   21
8    9   13   22

A    object
B    object
C    object
dtype: object

In [40]:
# Check for missing values
print("\n Missing Values Count: ")
print(df.isnull().sum())

 Missing Values Count:
A    3
B    3
C    3
dtype: int64

In [41]:
#Droppoing missing value
df.dropna()

   A   B   C
8  9  13  22

In [46]:
#Imputing Missing Values: Uses .fillna(df.mean()) to replace NaN with the mean of each column.
df = df.apply(pd.to_numeric , errors='coerce')  # Convert all columns to numeric, coercing errors to NaN
df_impute = df.fillna(df.mean(numeric_only=True))
print(df_impute)

     A          B          C
0  1.0   5.000000  18.666667
1  2.0   8.833333  15.000000
2  5.0   7.000000  16.000000
3  4.0   8.000000  18.666667
4  5.0   9.000000  18.000000
5  6.0   8.833333  18.666667
6  5.0  11.000000  20.000000
7  8.0   8.833333  21.000000
8  9.0  13.000000  22.000000